stages:
  - test
  - deploy

test:
  image: node:14.8
  only:
    - merge_requests
  script:
    - npm install
    - npm run build
    - npm run lint
    - npm run test-once

deploy:
  image: node:14.8
  only:
    refs:
      - master
  script:
    - npm install
    - npm run build
    - npm run lint
    - npm run test-once
    - npm run publish
